# Generated by Django 2.2.6 on 2019-10-16 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 18, 13, 1, 373948, tzinfo=utc)),
        ),
    ]
